name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-22.04
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: 16.16.186.92
          port: 22
          username: learnerplanet
          key: ${{secrets.PRIVATE_KEY}}
          script: "cd www; git pull origin main"
